### ISSUE TITLE
While adding songs in playlist should have select all option

### ISSUE THREAD

**Issue by Kathuria** [SharrySivia/Play.it#3]
Nice Work!

While adding songs in playlist, we should have option to add all tracks. This will save user time if they are going to select all tracks.

**Comment by Kathuria** [comment]
@SharrySivia/ @sandeep-chahal : Can I work on this issue, it will look like this

![Select All](https://user-images.githubusercontent.com/19428377/95655530-c31bb300-0b25-11eb-977c-9ba0ca0df1d6.PNG)

**Comment by SharrySivia** [comment]
@Kathuria I am working on this.

**Comment by Kathuria** [comment]
@SharrySivia : Can you please review the changes, if looks good can merge else feel free to discard. Actually, I haven't seen your comment and raised PR and noticed issue already closed.

Changes Link - https://github.com/SharrySivia/Play.it/pull/4/files 

+ Updated favicon from default React

Final Version supporting theme black.
![Final](https://user-images.githubusercontent.com/19428377/95658781-958d3480-0b3a-11eb-8228-7f151a973ad5.PNG)
